version: "3"
services:
  apache:
    image: nimmis/apache-php7
    ports:
      - "80:80"
    volumes:
      - "/data/bank/code:/var/www/html"
    links:
      - "mysql:database"
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=bank"
    volumes:
      - "bank_db:/var/lib/mysql"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      environment:
       - "MYSQL_ROOT_PASSWORD=root"
      links:
        - "mysql:db"
volumes:
 bank_db: